// Rebuilds countries-data.js from upstream sources. Run weekly by CI.
//   - attributes/flags/codes : mledoze/countries (MIT) + flagcdn.com
//   - population             : World Bank SP.POP.TOTL (most recent)
//   - passport rank/score    : ilyankou/passport-index-dataset (scraped from passportindex.org)
//   - passport cover image   : passportindex.org (by 2-letter code)
//   - image fallback (alt)   : preserved from the existing countries-data.js (Wikimedia URLs)
import { readFileSync, writeFileSync, existsSync } from 'fs';

const COUNTRIES = 'https://raw.githubusercontent.com/mledoze/countries/master/countries.json';
const WB = 'https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=json&per_page=400&mrnev=1';
const PASS = 'https://raw.githubusercontent.com/ilyankou/passport-index-dataset/master/passport-index-tidy-iso3.csv';
const OUT = 'countries-data.js';

const [all, wbRaw, passCsv] = await Promise.all([
  fetch(COUNTRIES).then(r => r.json()),
  fetch(WB).then(r => r.json()),
  fetch(PASS).then(r => r.text())
]);

// Preserve existing Wikimedia fallback URLs (passportImageAlt) by ISO3
const altByCca3 = {};
if (existsSync(OUT)) {
  try {
    const prev = new Function(readFileSync(OUT, 'utf8') + '; return COUNTRIES_DATA;')();
    prev.forEach(c => { if (c.cca3 && c.passportImageAlt) altByCca3[c.cca3] = c.passportImageAlt; });
  } catch (e) { console.log('Could not read previous data:', e.message); }
}

// Population
const popByIso3 = {};
wbRaw[1].forEach(row => { if (row.countryiso3code && row.value != null) popByIso3[row.countryiso3code] = row.value; });
const POP_OVERRIDES = { TWN:23420000,UNK:1761985,VAT:764,ESH:565581,GUF:290691,GLP:395700,MTQ:364508,REU:873102,MYT:320901,COK:15040,NIU:1937,FLK:3662,TKL:1893,WLF:11558,SHN:5314,BLM:10994,MAF:38659,SPM:5840,MSR:4922,AIA:15753,ALA:30129,GGY:63950,JEY:103267,NFK:2188,PCN:47,BVT:0,CXR:1692,CCK:593,BES:26221,SGS:30,IOT:3000,ATF:150,HMD:0,UMI:300 };
Object.keys(POP_OVERRIDES).forEach(k => { if (popByIso3[k] == null) popByIso3[k] = POP_OVERRIDES[k]; });

// Passport visa-free score + global rank
const ACCESS = new Set(['visa free', 'visa on arrival', 'eta']);
const scoreByIso3 = {};
passCsv.split(/\r?\n/).slice(1).forEach(line => {
  const p = line.split(','); if (p.length < 3) return;
  const passport = p[0].trim(), req = p[2].trim(); if (!passport) return;
  if (scoreByIso3[passport] == null) scoreByIso3[passport] = 0;
  if (ACCESS.has(req) || /^\d+$/.test(req)) scoreByIso3[passport] += 1;
});
const uniq = [...new Set(Object.values(scoreByIso3))].sort((a, b) => b - a);
const rankOf = {}; uniq.forEach((s, i) => { rankOf[s] = i + 1; });
const PASS_ALIAS = { UNK: 'XKX' };

const slim = all.map(c => {
  const cca2 = (c.cca2 || '').toLowerCase();
  const iso3 = c.cca3 || '';
  const passKey = scoreByIso3[iso3] != null ? iso3 : (PASS_ALIAS[iso3] || iso3);
  let passport = null;
  if (scoreByIso3[passKey] != null) { const vf = scoreByIso3[passKey]; passport = { visaFree: vf, rank: rankOf[vf] }; }
  return {
    name: { common: c.name && c.name.common, official: c.name && c.name.official },
    ccn3: c.ccn3 || '', cca3: iso3, cca2: cca2,
    region: c.region || '', subregion: c.subregion || '',
    capital: Array.isArray(c.capital) ? c.capital : [],
    population: popByIso3[iso3] != null ? popByIso3[iso3] : null,
    latlng: Array.isArray(c.latlng) ? c.latlng : null,
    currencies: c.currencies || {}, languages: c.languages || {},
    flags: cca2 ? { svg: 'https://flagcdn.com/' + cca2 + '.svg', png: 'https://flagcdn.com/w320/' + cca2 + '.png' } : { svg: '', png: '' },
    passportImage: (passport && cca2) ? 'https://img.passportindex.org/countries/' + cca2 + '.png' : '',
    passportImageAlt: altByCca3[iso3] || '',
    passport: passport
  };
});

console.log('countries', slim.length, '| with passport', slim.filter(c => c.passport).length, '| with image', slim.filter(c => c.passportImage).length);
writeFileSync(OUT,
  '// Bundled country data — auto-generated by scripts/build-data.mjs (weekly CI). Do not edit by hand.\n' +
  '// Sources: mledoze/countries (MIT), flagcdn.com, World Bank (SP.POP.TOTL),\n' +
  '// passport-index-dataset (rank), passportindex.org (cover images) with Wikimedia fallback.\n' +
  'var COUNTRIES_DATA = ' + JSON.stringify(slim) + ';\n', 'utf8');
console.log('wrote', OUT);
